### ISSUE TITLE
Allow renaming of the aggregate output fields

### ISSUE THREAD

**Issue by eranra** [netobserv/flowlogs-pipeline#15]
Allow flexibility to aggregate output fields. For example today the name "aggregate" is hardcoded, we want to allow changing the name of the field

**Comment by eranra** [comment]
@KalmanMeth can this be closed?? 

if I understand correctly with the new customizable pipline capabilities we can add "transform generic" post and modify field names?

**Comment by eranra** [comment]
@KalmanMeth maybe there is a missing feature to get all fields and modify only subset --- today we need to specify all fields that we want to generate as output and we do not have "copy all input fields to output fields" ... right>?? this might be needed

**Comment by KalmanMeth** [comment]
This feature is now covered by the transform_generic module. PR #156
