### ISSUE TITLE
Allow transform_generic to keep existing fields

### ISSUE THREAD

**Issue by amorenoz** [netobserv/flowlogs-pipeline#151]
Currently transform_generic removes all fields from the flow if you don't explicitly set them in the configuration.
This makes it's usage quite limited because you have to know exactly all the fields that the log will contain or you cannot modify a single field. It would be great to have that behavior configurable through a flag.

Another option would be to have `transform_generic` as a simple field rewrite (without removing fields that are not explicitly set) and have another transformation stage where you can select the fields you want for your log. It could have a more semantically intuitive name such as `filter`or `select`

**Comment by jotak** [comment]
sounds like a good enhancement to do, cc @eranra @KalmanMeth

**Comment by KalmanMeth** [comment]
When the transform_generic was first written I had in mind that it would completely transform the input to some standard internal format. However, we can do whatever we now think is most appropriate, and update the unit tests accordingly.

**Comment by amorenoz** [comment]
The problem with the current approach is that it limits the extensibility of the flow pipeline. If the flow exporter supports an additional field (through a newly defined template), we have to add it to the transform config list or else the new field will not be present in the log.

**Comment by eranra** [comment]
#156 provides the needed functionality.

@joel **if needed** you can modify NOO configuration to use this updated behavior
