### ISSUE TITLE
Flaky E2E tests

### ISSUE THREAD

**Issue by mariomac** [netobserv/flowlogs-pipeline#162]
I got two types of failure:
* [The test times out before building all the docker images](https://github.com/netobserv/flowlogs-pipeline/runs/5737911500?check_suite_focus=true)
* [Strimzi is not completely deployed when the Kafka tests start](https://github.com/netobserv/flowlogs-pipeline/runs/5737536548?check_suite_focus=true)

**Comment by eranra** [comment]
-> timeout issue addressed in #163

**Comment by KalmanMeth** [comment]
added longer timeouts.
Fixed strimzi deployment.
