### ISSUE TITLE
Make syntax of config yaml file entries consistent

### ISSUE THREAD

**Issue by KalmanMeth** [netobserv/flowlogs-pipeline#197]
We use different types of syntax in the config yaml file.
here is a short clip of the yaml file showing the different types of syntax we use.

      - input: bytes
        output: all
        type: add_if
        parameters: '>=0'
      - input: dstIP
        output: dstLocation
        type: add_location
        parameters: ""
    type: network
- extract:
    aggregates:
    - Name: bandwidth_network_service
      By:
      - service
      Operation: sum
      RecordKey: bytes

We should strive to have a uniform type of syntax for the different parts of the yaml file.

**Comment by jotak** [comment]
@KalmanMeth I think #213 has addressed this issue
