### ISSUE TITLE
There are some inconsistencies in the API

### ISSUE THREAD

**Issue by jotak** [netobserv/flowlogs-pipeline#206]
The [api](https://github.com/netobserv/flowlogs-pipeline/blob/main/docs/api.md) is not fully consistent, some names are `camelCase`, other `lowcase` and sometimes `snake_case`, e.g:
- `valuekey`
- `expirytime`
- `readTimeout`
- `batchSize`
- `buffer_length`

We should agree on a convention to follow

**Comment by jotak** [comment]
cc @KalmanMeth @ronensc @eranra

**Comment by ronensc** [comment]
I thought we had an issue for this, but I can't find it

**Comment by jotak** [comment]
> I thought we had an issue for this, but I can't find it

Ah, maybe this: https://github.com/netobserv/flowlogs-pipeline/issues/197

**Comment by ronensc** [comment]
@jotak we thought to use `camelCase` like in k8s. WDYT? do you have any preference?

**Comment by jotak** [comment]
> @jotak we thought to use `camelCase` like in k8s. WDYT? do you have any preference?

+1, it sounds more natural to me too

**Comment by jotak** [comment]
closed by #213
