### ISSUE TITLE
conntrack: Support `BiFlowDirection` field of IPFIX

### ISSUE THREAD

**Issue by ronensc** [netobserv/flowlogs-pipeline#281]
Currently, the conntrack module assumes the initiator of a connection is like the source of the first flow log.

In IPFIX, there is a field to determine the direction of the flow: `BiFlowDirection`.
According to [RFC5103](https://datatracker.ietf.org/doc/html/rfc5103#section-6.3), it has the following values:
```
   +-------+------------------+----------------------------------------+
   | Value | Name             | Description                            |
   +-------+------------------+----------------------------------------+
   | 0x00  | arbitrary        | Direction was assigned arbitrarily.    |
   | 0x01  | initiator        | The Biflow Source is the flow          |
   |       |                  | initiator, as determined by the        |
   |       |                  | Metering Process' best effort to       |
   |       |                  | detect the initiator.                  |
   | 0x02  | reverseInitiator | The Biflow Destination is the flow     |
   |       |                  | initiator, as determined by the        |
   |       |                  | Metering Process' best effort to       |
   |       |                  | detect the initiator.  This value is   |
   |       |                  | provided for the convenience of        |
   |       |                  | Exporting Processes to revise an       |
   |       |                  | initiator estimate without re-encoding |
   |       |                  | the Biflow Record.                     |
   | 0x03  | perimeter        | The Biflow Source is the endpoint      |
   |       |                  | outside of a defined perimeter.  The   |
   |       |                  | perimeter's definition is implicit in  |
   |       |                  | the set of Biflow Source and Biflow    |
   |       |                  | Destination addresses exported in the  |
   |       |                  | Biflow Records.                        |
   +-------+------------------+----------------------------------------+
```

AFAIU, currently the `BiFlowDirection` is set to "0" for all incoming flow logs from ovn-kubernetes. But, if it is set, it could make the aggregation of the conntrack module incorrect.
For example, consider the following flow logs:
|# |  Src  |  Dst  |  Bytes  |  BiFlowDirection  |
|--|-------|-------|---------|-------------------|
|1 | A     |   B   |   100   |   0               |
|2 | A     |   B   |   200   |   0               |

The output of the conntrack module will look like:
|# |  Src  |  Dst  |  Bytes_AB  |  Bytes_BA  |
|--|-------|-------|------------|------------|
|1 | A     |   B   |   300      |   0        |

And now, if the `BiFlowDirection` is set
|# |  Src  |  Dst  |  Bytes  |  BiFlowDirection  |
|--|-------|-------|---------|-------------------|
|1 | A     |   B   |   100   |   1               |
|2 | A     |   B   |   200   |   2               |

The output of the conntrack module will look as before (which is incorrect). The correct output is:
|# |  Src  |  Dst  |  Bytes_AB  |  Bytes_BA  |
|--|-------|-------|------------|------------|
|1 | A     |   B   |   100      |   200      |

**Comment by eranra** [comment]
@ronensc thanks for raising that issue :-) 

@jotak @jpinsonneau  @andrew-ronaldson @amorenoz  Hi, you might want to step in here and advise ^^^

**Comment by jotak** [comment]
@ronensc in your example here
|# |  Src  |  Dst  |  Bytes  |  BiFlowDirection  |
|--|-------|-------|---------|-------------------|
|1 | A     |   B   |   100   |   1               |
|2 | A     |   B   |   200   |   2               |

I think it should actually be two _different_ connections, because it is telling you that in flow 1, A is the initiator, and in flow 2, B is the initiator. So if there's two initiators, there's two connections, no?

I think a more common case would be to see:
|# |  Src  |  Dst  |  Bytes  |  BiFlowDirection  |
|--|-------|-------|---------|-------------------|
|1 | A     |   B   |   100   |   1               |
|2 | B     |   A   |   200   |   2               |


But, for the record, with OVS this field is unused, so it has no impact in NetObserv at least for what we support "officially".

**Comment by ronensc** [comment]
> I think it should actually be two different connections, because it is telling you that in flow 1, A is the initiator, and in flow 2, B is the initiator. So if there's two initiators, there's two connections, no?

I probably misunderstood the RFC and you're correct.
Anyway, if it's unused by OVS, I guess we can leave this issue for later...

**Comment by KalmanMeth** [comment]
No longer relevant.
