### ISSUE TITLE
Detect end connections by TCP flags

### ISSUE THREAD

**Issue by ronensc** [netobserv/flowlogs-pipeline#299]
In the current implementation of the connection tracking, a connection is considered ended if a configurable timeout since the last flow-log of the connection has expired.
For protocols like TCP, we can determine that a connection has ended by inspecting its TCP flags (`FIN` flag) and cut the timeout.

This is also related to:
https://issues.redhat.com/browse/NETOBSERV-569

cc @jotak @eranra

**Comment by eranra** [comment]
@mariomac @praveingk do you need to refer to this issue from a new one under the agent repo (or Jira?)

**Comment by praveingk** [comment]
@ronensc @jotak @eranra @mariomac : Apart from FIN/RST, Are there other use-cases planned for connection tracking?
I initially had the logic to evict on FIN/RST, but we wanted to keep the v2 simple and introduce that as part of a bigger connection tracking feature. 
Some questions : 
1) From ebpf agent, do you need only the TCP Flags? are there more info needed?
2) If only TCP Flags? Do we want to track events like "who initiated the connection", "who closed it", etc?
3) Do we need other states like window size (16 bit), which are useful for performance analysis?

**Comment by jotak** [comment]
> If only TCP Flags? Do we want to track events like "who initiated the connection", "who closed it", etc?
"Who initiated the connection" can be deduced from the flow w/ flags, right? Source IP on SYN == initiator?

**Comment by praveingk** [comment]
Yes, I meant TCP flags could be used to answer those questions in userspace
