### ISSUE TITLE
Decouple reporting of operational metrics from network metrics

### ISSUE THREAD

**Issue by jotak** [netobserv/flowlogs-pipeline#302]
JIRA: https://issues.redhat.com/browse/NETOBSERV-579

The metric prefix defined in PromEncode stage currently doesn't apply to operational metrics.
We should find a way to reuse it, or provide an alternative prefix configuration for those metrics.

(In the context of the operator, we want to prefix everything "netobserv_")

cc @KalmanMeth @eranra @ronensc

**Comment by jotak** [comment]
Actually, I think the prom config api doe not work well with operational metrics as it is designed. I think we should split the prom's server config out of the pipeline parameters, and move it as a global parameter instead. WDYT?

The reason is that the same metrics server is actually used for operational metrics and promencode metrics, which does not allow:
- to have operational metrics when no promencode stage is configured
- to have more than one promencode stage in the pipeline

**Comment by KalmanMeth** [comment]
@jotak So you are suggesting that we always initialize the global prom parameters (port number, prefix). If there is no encode-prom stage, we will still generate operational metrics. If we want to make the prefix configurable, then we need to introduce a new mechanism to specify configuration parameters that are not part of any stage.

**Comment by KalmanMeth** [comment]
To define config parameters that are not part of a particular stage, we should have a section in the yaml outside of the `parameters` and `pipeline` sections; perhaps a global `config` section. In this section we could define the global prometheus prefix and port number.
Perhaps in the prom-encode section, besides the specific rules, we could allow an override of the globally defined prefix and port number.
If we allow more than one prometheus encoder and we want it enabled in the Operator, then we would have to think how to change the Operator configuration to include such an option.

**Comment by jotak** [comment]
see #314 for just the prefix change. We can keep this issue opened for further changes, e.g. starting prom server for operational metrics even without a PromEncode stage configured
