### ISSUE TITLE
Allow to limit the memory used by FLP

### ISSUE THREAD

**Issue by KalmanMeth** [netobserv/flowlogs-pipeline#374]
The memory usage of FLP seems to grow linearly with the number of concurrent connections being handled at the same time.
For encode_prom, state is saved (both in FLP and in the prometheus Go client) for each metric/labels combination that is reported. This results in memory growth that is linear with respect to the number of connections currently identified as active. In a configuration with limited memory resources it is desirable to instruct FLP to limit the amount of memory usage.
The tradeoff would be to not report on new connections once the memory limit is hit.

**Comment by eranra** [comment]
@KalmanMeth, thanks for opening :-) We must add a metric that indicates how much we missed, so there will be a possibility to track that and indicate that FLP is not in maximum functionality.
