### ISSUE TITLE
NETOBSERV-1111: Add support for RTT

### ISSUE THREAD

**Issue by KalmanMeth** [netobserv/flowlogs-pipeline#439]
See https://github.com/netobserv/netobserv-ebpf-agent/pull/117

**Comment by dushyantbehl** [comment]
Tracked here -  https://github.com/netobserv/flowlogs-pipeline/pull/446

**Comment by dushyantbehl** [comment]
Solved by https://github.com/netobserv/flowlogs-pipeline/pull/446
