### ISSUE TITLE
Align version to RH versioning scheme 

### ISSUE THREAD

**Issue by eranra** [netobserv/flowlogs-pipeline#97]
- make sure that we expose the version when running the code.
- expose compile time 
- expose commit so we can always go to that commit

**Comment by eranra** [comment]
@jotak FYI ^^^

**Comment by jotak** [comment]
Yes, good point.
Also, we'll have to take prow into the game, for the CI. And we use to create image tags based on branches in quay, e.g. we have tags `main` and `release-4.10` (which ties to the openshift release)
We can talk about that tomorrow

**Comment by jotak** [comment]
FYI I created https://quay.io/repository/netobserv/flowlogs-pipeline
